[xemacs-hg @ 2005-11-28 09:50:16 by crestani] Remove vdb-fake warning, die if POSIX checks fail.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -30040,6 +30040,8 @@ fi
   if test "$have_vdb_sigaction" != "yes" -a "$have_vdb_signal" != "yes" ; then
     have_vdb_posix=no
     have_vdb_fake=yes
+    { echo "Error:" "No working write-barrier implementation found for this system.
+       Please report this and provide information about your system." >&2; exit 1; }
   else
     have_vdb_posix=yes
     have_vdb_fake=no
@@ -39336,15 +39338,6 @@ if test "$have_vdb_win32" = yes ; then
 fi
 if test "$have_vdb_mach" = yes ; then
   echo "  Using mach exception mechanism as vdb fault handler."
-fi
-if test "$have_vdb_fake" = yes && test "$enable_vdb" != fake; then
-  echo "  WARNING: ---------------------------------------------------------"
-  echo "  WARNING: The new incremental garbage collector is enabled, but"
-  echo "  WARNING: a virtual dirty bit implementation is not yet available"
-  echo "  WARNING: on this system. XEmacs will crash if you try to switch on"
-  echo "  WARNUNG: incremental garbage collection!"
-  echo "  WARNING: Use \`--disable-newgc' to turn incremental gc off."
-  echo "  WARNING: ---------------------------------------------------------"
 fi
 if test "$have_vdb_fake" = yes && test "$enable_vdb" == fake; then
   echo "  Virtual dirty bit write barrier manually disabled."
