[xemacs-hg @ 2006-03-27 21:00:01 by james] Fix ALSA detection by detecting a header file with no dependencies.  See xemacs-patches message with ID <m3vetzvc39.fsf@jerrypc.cs.usu.edu>.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -35584,18 +35584,18 @@ _ACEOF
 fi
 
 if test "$enable_sound_alsa" != "no"; then
-  if test "${ac_cv_header_alsa_pcm_h+set}" = set; then
-  echo "$as_me:$LINENO: checking for alsa/pcm.h" >&5
-echo $ECHO_N "checking for alsa/pcm.h... $ECHO_C" >&6
-if test "${ac_cv_header_alsa_pcm_h+set}" = set; then
+  if test "${ac_cv_header_alsa_input_h+set}" = set; then
+  echo "$as_me:$LINENO: checking for alsa/input.h" >&5
+echo $ECHO_N "checking for alsa/input.h... $ECHO_C" >&6
+if test "${ac_cv_header_alsa_input_h+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 fi
-echo "$as_me:$LINENO: result: $ac_cv_header_alsa_pcm_h" >&5
-echo "${ECHO_T}$ac_cv_header_alsa_pcm_h" >&6
+echo "$as_me:$LINENO: result: $ac_cv_header_alsa_input_h" >&5
+echo "${ECHO_T}$ac_cv_header_alsa_input_h" >&6
 else
   # Is the header compilable?
-echo "$as_me:$LINENO: checking alsa/pcm.h usability" >&5
-echo $ECHO_N "checking alsa/pcm.h usability... $ECHO_C" >&6
+echo "$as_me:$LINENO: checking alsa/input.h usability" >&5
+echo $ECHO_N "checking alsa/input.h usability... $ECHO_C" >&6
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -35603,7 +35603,7 @@ cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 $ac_includes_default
-#include <alsa/pcm.h>
+#include <alsa/input.h>
 _ACEOF
 rm -f conftest.$ac_objext
 if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
@@ -35639,15 +35639,15 @@ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
 echo "${ECHO_T}$ac_header_compiler" >&6
 
 # Is the header present?
-echo "$as_me:$LINENO: checking alsa/pcm.h presence" >&5
-echo $ECHO_N "checking alsa/pcm.h presence... $ECHO_C" >&6
+echo "$as_me:$LINENO: checking alsa/input.h presence" >&5
+echo $ECHO_N "checking alsa/input.h presence... $ECHO_C" >&6
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-#include <alsa/pcm.h>
+#include <alsa/input.h>
 _ACEOF
 if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
   (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
@@ -35681,25 +35681,25 @@ echo "${ECHO_T}$ac_header_preproc" >&6
 # So?  What about this header?
 case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
   yes:no: )
-    { echo "$as_me:$LINENO: WARNING: alsa/pcm.h: accepted by the compiler, rejected by the preprocessor!" >&5
-echo "$as_me: WARNING: alsa/pcm.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
-    { echo "$as_me:$LINENO: WARNING: alsa/pcm.h: proceeding with the compiler's result" >&5
-echo "$as_me: WARNING: alsa/pcm.h: proceeding with the compiler's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: alsa/input.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: alsa/input.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: alsa/input.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: alsa/input.h: proceeding with the compiler's result" >&2;}
     ac_header_preproc=yes
     ;;
   no:yes:* )
-    { echo "$as_me:$LINENO: WARNING: alsa/pcm.h: present but cannot be compiled" >&5
-echo "$as_me: WARNING: alsa/pcm.h: present but cannot be compiled" >&2;}
-    { echo "$as_me:$LINENO: WARNING: alsa/pcm.h:     check for missing prerequisite headers?" >&5
-echo "$as_me: WARNING: alsa/pcm.h:     check for missing prerequisite headers?" >&2;}
-    { echo "$as_me:$LINENO: WARNING: alsa/pcm.h: see the Autoconf documentation" >&5
-echo "$as_me: WARNING: alsa/pcm.h: see the Autoconf documentation" >&2;}
-    { echo "$as_me:$LINENO: WARNING: alsa/pcm.h:     section \"Present But Cannot Be Compiled\"" >&5
-echo "$as_me: WARNING: alsa/pcm.h:     section \"Present But Cannot Be Compiled\"" >&2;}
-    { echo "$as_me:$LINENO: WARNING: alsa/pcm.h: proceeding with the preprocessor's result" >&5
-echo "$as_me: WARNING: alsa/pcm.h: proceeding with the preprocessor's result" >&2;}
-    { echo "$as_me:$LINENO: WARNING: alsa/pcm.h: in the future, the compiler will take precedence" >&5
-echo "$as_me: WARNING: alsa/pcm.h: in the future, the compiler will take precedence" >&2;}
+    { echo "$as_me:$LINENO: WARNING: alsa/input.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: alsa/input.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: alsa/input.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: alsa/input.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: alsa/input.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: alsa/input.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: alsa/input.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: alsa/input.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: alsa/input.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: alsa/input.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: alsa/input.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: alsa/input.h: in the future, the compiler will take precedence" >&2;}
     (
       cat <<\_ASBOX
 ## ------------------------------------- ##
@@ -35710,18 +35710,18 @@ _ASBOX
       sed "s/^/$as_me: WARNING:     /" >&2
     ;;
 esac
-echo "$as_me:$LINENO: checking for alsa/pcm.h" >&5
-echo $ECHO_N "checking for alsa/pcm.h... $ECHO_C" >&6
-if test "${ac_cv_header_alsa_pcm_h+set}" = set; then
+echo "$as_me:$LINENO: checking for alsa/input.h" >&5
+echo $ECHO_N "checking for alsa/input.h... $ECHO_C" >&6
+if test "${ac_cv_header_alsa_input_h+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  ac_cv_header_alsa_pcm_h=$ac_header_preproc
+  ac_cv_header_alsa_input_h=$ac_header_preproc
 fi
-echo "$as_me:$LINENO: result: $ac_cv_header_alsa_pcm_h" >&5
-echo "${ECHO_T}$ac_cv_header_alsa_pcm_h" >&6
+echo "$as_me:$LINENO: result: $ac_cv_header_alsa_input_h" >&5
+echo "${ECHO_T}$ac_cv_header_alsa_input_h" >&6
 
 fi
-if test $ac_cv_header_alsa_pcm_h = yes; then
+if test $ac_cv_header_alsa_input_h = yes; then
 
     echo "$as_me:$LINENO: checking for snd_pcm_open in -lasound" >&5
 echo $ECHO_N "checking for snd_pcm_open in -lasound... $ECHO_C" >&6
